"""机械臂执行器协议。"""

from __future__ import annotations

from typing import Protocol

from ..models import ExecutionResult, SingleMovePlan


class RobotExecutor(Protocol):
    def initialize(self) -> None: ...
    def move_to_observe_pose(self) -> None: ...
    def notify_completion(self) -> None: ...
    def wait_until_idle(self, timeout_s: float) -> bool: ...
    def execute_single_move(self, plan: SingleMovePlan, magnet) -> ExecutionResult: ...
    def emergency_stop(self) -> None: ...
    def close(self) -> None: ...
