"""第二问配置：现场未知碎片 + 可变目标矩形"""

# A4（与第一问相同）
A4_WIDTH_CM = 21.0
A4_HEIGHT_CM = 29.7
DIVIDER_Y_CM = A4_HEIGHT_CM / 2

# 目标矩形允许范围 (cm)
TARGET_WIDTH_MIN_CM = 9.0
TARGET_WIDTH_MAX_CM = 12.0
TARGET_HEIGHT_MIN_CM = 5.0
TARGET_HEIGHT_MAX_CM = 9.0

# 目标区默认放置（下半区居中，尺寸运行时确定）
TARGET_ORIGIN_X_CM = (A4_WIDTH_CM - 10.5) / 2  # 随 W 调整
TARGET_ORIGIN_Y_CM = DIVIDER_Y_CM + 2.0

# 现场碎片约束
MAX_PIECES = 5  # 赛题上限 4；本地测试可生成 5 片
MIN_PIECES = 1
MAX_VERTICES = 5
MIN_EDGE_CM = 2.0
MIN_PIECE_AREA_CM2 = 3.0
MAX_PIECE_AREA_CM2 = 80.0

# 评分
VERTEX_MATCH_TOLERANCE_CM = 2.0
AREA_SUM_TOLERANCE = 0.12  # 面积之和与 W*H 允许相对误差

# 视觉（黑底白片）
HSV_PIECES = [((0, 0, 120), (180, 100, 255))]
DEFAULT_HSV_RANGES = HSV_PIECES
BLACK_PAPER_GRAY_THRESH = 90
WHITE_DIVIDER_GRAY_THRESH = 160

MIN_PIECE_AREA_CM2_DETECT = 1.0
MAX_DETECT_PIECE_AREA_CM2 = 55.0

# 求解
EDGE_LENGTH_TOL_CM = 0.75
ANGLE_TOL_DEG = 8.0

# 运行
CAMERA_INDEX = 0
CAMERA_WIDTH = 848
CAMERA_HEIGHT = 480
DISPLAY_SCALE = 0.65
SERIAL_PORT = ""
SERIAL_BAUD = 115200
SERIAL_TIMEOUT_S = 30.0
FORCE_DRY_RUN = False
STEP_DELAY_S = 2.0
VERIFY_DELAY_S = 1.5
